version: "3.0"
services:
  db:
    image: mysql:5.7.19
    environment:
      - MYSQL_DATABASE=loja
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    VOLUME [ "/data" ]
# minikube/Dockerfile 

# FROM node:6.14.2
# EXPOSE 8080
# COPY server.js .
# CMD [ "node", "server.js" ]
